# Generated by Django 2.0.6 on 2019-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190511_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='123456@qq.com', max_length=254, verbose_name='用户邮箱'),
        ),
    ]
