# Generated by Django 2.0.6 on 2019-05-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='用户邮箱'),
        ),
    ]
