# Generated by Django 2.0.6 on 2019-05-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190512_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='liaison',
            field=models.CharField(max_length=11, verbose_name='联系方式'),
        ),
    ]
