# Generated by Django 2.0.6 on 2019-05-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190513_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_number',
            field=models.CharField(max_length=20, null=True, verbose_name='门牌号'),
        ),
    ]
