# Generated by Django 2.0.6 on 2019-05-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190515_0314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('address_detailed', 'address_number')},
        ),
    ]
