# Generated by Django 2.0.6 on 2019-05-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190516_0124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('address_detailed', 'address_number', 'address_type')},
        ),
    ]
