# Generated by Django 2.0.6 on 2019-05-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190516_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='纬度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='address_longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='经度'),
            preserve_default=False,
        ),
    ]
