# Generated by Django 2.0.6 on 2019-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190516_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_detailed',
            field=models.CharField(max_length=50, verbose_name='地址'),
        ),
    ]
