# Generated by Django 2.0.6 on 2019-05-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userinfo_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_status',
            field=models.SmallIntegerField(choices=[(0, '超级管理员'), (1, '管理员'), (2, '普通用户')], default=2),
        ),
    ]
