# Generated by Django 2.0.6 on 2019-05-11 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '待取货'), (2, '配送中'), (3, '已完成'), (4, '已取消')], default=0)),
                ('demo', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=10.0, max_digits=7)),
                ('driver', models.CharField(default='嗖嗖骑手', max_length=10)),
                ('recv_addr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='o_recv', to='user.Address')),
                ('sender_addr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='o_send', to='user.Address')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
    ]
