# Generated by Django 2.0.6 on 2019-05-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190511_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, '现金'), (1, '在线支付')], default=1),
        ),
    ]
