# Generated by Django 2.0.6 on 2019-05-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stdmode',
            field=models.SmallIntegerField(choices=[(0, '食品饮料'), (1, '服饰鞋帽'), (2, '鲜花'), (3, '蛋糕'), (4, '文件'), (5, '水果生鲜'), (6, '证照证件'), (7, '数码家电'), (8, '其他')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='demo',
            field=models.CharField(max_length=50),
        ),
    ]
