# Generated by Django 2.0.6 on 2019-05-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190512_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.CharField(default='50元以下', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='stdmode',
            field=models.CharField(default='服饰鞋帽', max_length=10),
        ),
    ]
