# Generated by Django 2.0.6 on 2019-05-13 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190513_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recv_addr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='o_recv', to='user.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_addr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='o_send', to='user.Address'),
        ),
    ]
