# Generated by Django 2.0.6 on 2019-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190513_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='订单ID'),
        ),
    ]
