# Generated by Django 2.0.6 on 2019-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190516_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trade_no',
            field=models.CharField(default='', max_length=128, verbose_name='支付编号'),
        ),
    ]
