# Generated by Django 2.0.6 on 2019-05-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_trade_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待支付'), (1, '待接单'), (2, '待取货'), (3, '配送中'), (4, '已完成'), (5, '已取消')], default=0),
        ),
    ]
